#!/usr/bin/env python3

"""
This script is basically the contents of the 'fab' script.
It's here for convenience, since all simnet-workbench does
is basically invoke fabric.
"""

import sys
from fabric.main import program

if __name__ == "__main__":
    sys.exit(program.run())
